language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install pytest pytest-cov
install:
  - pip install .
  - pip install torch --progress-bar off
  - pip install torchvision --progress-bar off
  - pip install numpy --progress-bar off
  - pip install matplotlib --progress-bar off
  - pip install -r requirements.txt
# command to run tests
script: pytest